import Components from '.';
import AddressForm from './address/Address.form';
import ButtonForm from './button/Button.form';
import CheckboxForm from './checkbox/Checkbox.form';
import ColumnsForm from './columns/Columns.form';
import ComponentForm from './_classes/component/Component.form';
import ContainerForm from './container/Container.form';
import ContentForm from './content/Content.form';
import CurrencyForm from './currency/Currency.form';
import DataGridForm from './datagrid/DataGrid.form';
import DataMapForm from './datamap/DataMap.form';
import DateTimeForm from './datetime/DateTime.form';
import DayForm from './day/Day.form';
import EditGridForm from './editgrid/EditGrid.form';
import EmailForm from './email/Email.form';
import FieldsetForm from './fieldset/Fieldset.form';
import FileForm from './file/File.form';
import FormForm from './form/Form.form';
import ListForm from './_classes/list/ListComponent.form';
import HiddenForm from './hidden/Hidden.form';
import HtmlElementForm from './html/HTML.form';
import NestedForm from './_classes/nested/NestedComponent.form';
import NumberForm from './number/Number.form';
import PanelForm from './panel/Panel.form';
import PasswordForm from './password/Password.form';
import PhoneNumberForm from './phonenumber/PhoneNumber.form';
import RadioForm from './radio/Radio.form';
import ReCaptchaForm from './recaptcha/ReCaptcha.form';
import ResourceForm from './resource/Resource.form';
import SelectboxesForm from './selectboxes/SelectBoxes.form';
import SelectForm from './select/Select.form';
import SignatureForm from './signature/Signature.form';
import SurveyForm from './survey/Survey.form';
import TableForm from './table/Table.form';
import TabsForm from './tabs/Tabs.form';
import TagsForm from './tags/Tags.form';
import TextAreaForm from './textarea/TextArea.form';
import TextfieldForm from './textfield/TextField.form';
import TimeForm from './time/Time.form';
import TreeForm from './tree/Tree.form';
import UnknownForm from './unknown/Unknown.form';
import UrlForm from './url/Url.form';
import WellForm from './well/Well.form';
import DataForm from './Data/Data.form';
import ChartForm from './Chart/Chart.form';
import CustomCheckBoxForm from './CustomCheckBox/CustomCheckBox.form';
import CustomDateTimeForm from './CustomDateTime/CustomDateTime.form';
import CustomFileForm from './CustomFile/CustomFile.form';
import CustomUrlForm from './CustomUrl/CustomUrl.form';
import CustomRadioForm from './CustomRadio/CustomRadio.form';
import CustomSelectForm from './CustomSelect/CustomSelect.form';
import CustomTextAreaForm from './CustomTextArea/CustomTextArea.form';
import CustomTextFieldForm from './CustomTextField/CustomTextField.form';
import ProcessTableForm from './ProcessTable/ProcessTable.form';
import DepartmentForm from './Department/Department.form';
import FlexForm from './Flex/Flex.form';
import NewsDataForm from './NewsData/NewsData.form';
import QrCodeForm from './QrCode/QrCode.form';
import ScanInputTextFieldForm from './ScanInputTextField/ScanInputTextField.form';
import ActionButtonForm from './ActionButton/ActionButton.form';
import HtmlEditorForm from './wysiwyg/TextArea.form';
import FileDownloadForm from './FileDownload/FileDownload.form';
import TaskCalendarForm from './TaskCalendar/TaskCalendar.form';
import LocationInputTextFieldForm from './LocationInputTextField/LocationInputTextField.form';
import NocodbFileForm from './NocodbFile/NocodbFile.form';

Components.nocodbFile.editForm = NocodbFileForm;
Components.fileDownload.editForm = FileDownloadForm;
Components.htmlEditor.editForm = HtmlEditorForm;
Components.scanInputTextField.editForm = ScanInputTextFieldForm;
Components.qrCode.editForm = QrCodeForm;
Components.newsData.editForm = NewsDataForm;
Components.flex.editForm = FlexForm;
Components.data.editForm = DataForm;
Components.chart.editForm = ChartForm;
Components.edittable.editForm = EditGridForm;
Components.customDateTime.editForm = CustomDateTimeForm;
Components.customFile.editForm = CustomFileForm;
Components.customUrl.editForm = CustomUrlForm;
Components.customRadio.editForm = CustomRadioForm;
Components.customCheckBox.editForm = CustomCheckBoxForm;
Components.customSelect.editForm = CustomSelectForm;
Components.customTextArea.editForm = CustomTextAreaForm;
Components.customTextField.editForm = CustomTextFieldForm;
Components.processTable.editForm = ProcessTableForm;
Components.department.editForm = DepartmentForm;
Components.address.editForm = AddressForm;
Components.button.editForm = ButtonForm;
Components.checkbox.editForm = CheckboxForm;
Components.columns.editForm = ColumnsForm;
Components.component.editForm = ComponentForm;
Components.container.editForm = ContainerForm;
Components.content.editForm = ContentForm;
Components.currency.editForm = CurrencyForm;
Components.datagrid.editForm = DataGridForm;
Components.datamap.editForm = DataMapForm;
Components.datetime.editForm = DateTimeForm;
Components.day.editForm = DayForm;
Components.editgrid.editForm = EditGridForm;
Components.email.editForm = EmailForm;
Components.fieldset.editForm = FieldsetForm;
Components.file.editForm = FileForm;
Components.form.editForm = FormForm;
Components.list.editForm = ListForm;
Components.hidden.editForm = HiddenForm;
Components.htmlelement.editForm = HtmlElementForm;
Components.nested.editForm = NestedForm;
Components.number.editForm = NumberForm;
Components.panel.editForm = PanelForm;
Components.password.editForm = PasswordForm;
Components.phoneNumber.editForm = PhoneNumberForm;
Components.radio.editForm = RadioForm;
Components.recaptcha.editForm = ReCaptchaForm;
Components.resource.editForm = ResourceForm;
Components.select.editForm = SelectForm;
Components.selectboxes.editForm = SelectboxesForm;
Components.signature.editForm = SignatureForm;
Components.survey.editForm = SurveyForm;
Components.table.editForm = TableForm;
Components.tabs.editForm = TabsForm;
Components.tags.editForm = TagsForm;
Components.textarea.editForm = TextAreaForm;
Components.textfield.editForm = TextfieldForm;
Components.time.editForm = TimeForm;
Components.tree.editForm = TreeForm;
Components.unknown.editForm = UnknownForm;
Components.url.editForm = UrlForm;
Components.well.editForm = WellForm;
Components.actionButton.editForm = ActionButtonForm;
Components.taskCalendar.editForm = TaskCalendarForm;
Components.locationInputTextField.editForm = LocationInputTextFieldForm;

export default Components;
